# Generated by Django 5.1.5 on 2025-01-30 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('U', 'Used'), ('N', 'Brand New')], default='U', max_length=50)),
                ('transmission', models.CharField(choices=[('A', 'Automatic'), ('S', 'Semi Automatic'), ('M', 'Manual'), ('S', 'Sequential')], default='A', max_length=20)),
                ('fuel_type', models.CharField(choices=[('P', 'Petrol'), ('F', 'Fuel'), ('E', 'Electric'), ('H', 'Hybrid')], default='P', max_length=10)),
                ('description', models.TextField()),
                ('mileage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_body', models.CharField(max_length=50)),
                ('hp_power', models.CharField(max_length=50)),
                ('door', models.CharField(max_length=10)),
                ('traction', models.CharField(choices=[('F', 'FWD'), ('R', 'RWD'), ('4', '4WD'), ('A', 'AWD')], max_length=5)),
                ('steering', models.CharField(choices=[], default='R', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.car')),
            ],
        ),
    ]
