# Generated by Django 5.1.5 on 2025-01-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
